hello/config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :projects

  devise_for :users


  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :projects
  resources :teams
  resources :users

  root 'hello#index'

  get 'ps1_zerodiv', to: 'hello#zerodiv', as: 'zerodiv'

  get 'ps1_scrape', to: 'hello#scrape', as: 'scrape'

  get 'quotations', to: 'hello#quotations', as: 'quotations'

  post 'quotations', to: 'hello#quotations', as: 'quotations_post'

  get 'searchpage', to: 'hello#searchpage', as: 'quotations_search'

  get 'ps2_solutions', to: 'hello#ps2_solutions', as: 'ps2_sol'

  get 'ps3', to: 'hello#ps3', as: 'ps3'

  get 'ps4', to: 'hello#ps4', as: 'ps4'

  get 'ps5', to: 'hello#ps5', as: 'ps5'

  get 'ps6', to: 'hello#ps6', as: 'ps6'


  get 'admin_panel', to: 'hello#admin_panel', as: 'admin_panel'
  post 'admin_panel', to: 'hello#admin_panel', as: 'admin_panel_post'


end

hello/app/controllers/hello_controller.rb
require 'nokogiri'
require 'open-uri'

class HelloController < ApplicationController

	def index
		if user_signed_in?
			@teams = Team.where('id = ?', current_user.team_id)
			@projects = Project.where('team_id = ?', current_user.team_id)
		end
	end

	def zerodiv
		respond_to do |format|
			format.html {render :ps1_zerodiv}
		end
	end

	def scrape

		#Scraping Code:
		prox = "http://192.41.170.23:3128"
		url1 = 'https://www.foxnews.com/'
		doc1 = Nokogiri::HTML(URI.open(url1,proxy: URI.parse(prox)))
		@headline1 = doc1.css('main a picture img').attribute('alt').value
		#puts headline
		@img_url1 = doc1.css('main a picture img').attribute('src').value
	    #puts img_url
		@headurl_1 = doc1.css('main header a').attribute('href').value

		url2 = 'https://www.ndtv.com/'
		doc2 = Nokogiri::HTML(URI.open(url2,proxy: URI.parse(prox)))
		@headline2 = doc2.css('img.imgbrd').attribute('alt').value
		#puts headline2
		@img_url2 = doc2.css('img.imgbrd').attribute('src').value
	    #puts img_url2
		@headurl_2 = doc2.css('a').attribute('href').value


		respond_to do |format|
			format.html {render :ps1_scrape}
		end
	end
        

	def quotations

		if params[:quotation]
	      @quotation = Quotation.new(quote_params)

	      if params[:newcategory][:id]
	      	@quotation.category = params[:newcategory][:id]
	      	#@catt = params[:newcategory]
	      end


	      if @quotation.save
	        flash[:notice] = 'Quotation was successfully created.'
	        @quotation = Quotation.new
	      end

      	else
        	@quotation = Quotation.new
      	end

      	if(params[:erase])
      		cookies.permanent[:qno] = nil
      	end 

	    if params[:qno]
	    	if cookies[:qno]
	    		cookies.permanent[:qno] = cookies.permanent[:qno] + " " + params[:qno]
	    	else
	    		cookies.permanent[:qno] = params[:qno]
	    	end
	    end	

	    if params[:sort_by] == "date"
	      @quotations = Quotation.where.not(id: cookies.permanent[:qno]? cookies.permanent[:qno].split(" ") : nil).order(:created_at)
	    else
	      @quotations = Quotation.where.not(id: cookies.permanent[:qno]? cookies.permanent[:qno].split(" ") : nil).order(:category)

	    end


	    @exp = Quotation.all
		respond_to do |format|
			format.html
			format.json { render json: @exp }
			format.xml { render xml: @exp.map(&:as_json).to_xml }

		end

		if params[:xml_url]
			@xml_url = params[:xml_url]
			@doc3 = Nokogiri::XML(open(@xml_url))

			if @doc3

				@doc3.css('object').each do |node|
					children = node.children

				Quotation.create(
					#:id => node['id'].inner_text,
					:author_name => children.css('author-name').inner_text,
					:category => children.css('category').inner_text,
					:quote => children.css('quote').inner_text
				)

				end

			else
				flash.alert = "Incorrect URL"
			end
		end

	    #@search = Quotation.search(params[:search])
		#respond_to do |format|
		#	format.html {render :quotations}
		#end

		#@category_list = Quotation.select('DISTINCT category').where.not(category: [nil, ''])
	end

	def searchpage
		@quotations = Quotation.where.not(id: cookies.permanent[:qno]? cookies.permanent[:qno].split(" ") : nil).search(params[:search])

	end

	def ps2_solutions
	end


	def ps3
	end

	def ps4
	end

	def ps5

	end

	def ps6

	end

	def admin_panel
		if current_user.is_admin?
			@users = User.all
			if params[:uid]

				@person = User.find_by_id(params[:uid])

				if @person.is_active?
					@person.is_active = false
					flash[:notice] = "User has been banned"
				else
					@person.is_active = true
					flash[:notice] = "User has been activated"
				end
				@person.save
			end
		else
			flash[:alert] = "Nice try smarty pants!"
			redirect_to root_path
		end


	end







	private

	def quote_params
		params.require(:quotation).permit(:author_name, :category, :newcategory, :quote, :search)

	end




end

hello/app/helpers/hello_helper.rb
module HelloHelper
end

hello/app/views/hello/_dashboard.html.erb
<section class="section pt3">
  <p class="title is-5 border-bottom pb3 has-text-centered">Welcome <%= current_user.name %> 👋🏻</p>
  <div class="columns">

    <div class="column border-right ph4">
      <div class="level">
        <div class="level-left">
          <h3 class="subtitle is-5">My Projects <span class="tag is-rounded"><%= @projects.count %></span></h3>
        </div>
        <div class="level-right">
          <p class="field">
            <%= link_to new_project_path, class: 'button is-small' do %>
              <span class="icon is-small has-text-link"><i class="fa fa-plus"></i></span>
            <% end %>
          </p>
        </div>
      </div>
      <hr />
      <% @projects.each do |project| %>
        <div class="content border-bottom pb4">
          <p class="title is-4">
            <%= link_to project.name, project %>
          </p>
          <p class="subtitle is-6">
            <%= link_to project.team.name, project.team %>
          </p>
          <p class="f6">Created by: <%= project.user.name %></p>
        </div>
      <% end %>

    </div>
    <div class="column border-right ph4">
      <div class="level">
        <div class="level-left">
          <h3 class="subtitle is-5">My Teams <span class="tag is-rounded"><%= @teams.count %></span></h3>
        </div>
        <div class="level-right">
          <p class="field">
            <%= link_to new_team_path, class: 'button is-small' do %>
              <span class="icon is-small has-text-link"><i class="fa fa-plus"></i></span>
            <% end %>
          </p>
        </div>
      </div>
      <hr />
      <% @teams.each do |team| %>
        <div class="content border-bottom pb4">
          <p class="title is-4">
            <%= link_to team.name, team %>
          </p>
          <p class="subtitle is-6"><%= team.users.count %> Members</p>
          <span class="f6"><%= safe_join(team.users.map { |user| user.name }, ', ') %></span>
        </div>
      <% end %>

    </div>

    <div class="column ph4">
      <h3 class="subtitle is-5">Activity</h3>
      <hr />
      <ul class="list">
        <%#= render_activities(@activities) %>
      </ul>
    </div>

  </div>
</section>

hello/app/views/hello/_home.html.erb
</br>

<h3 class="title is-3">All Problem Sets are in the Navbar</h3>

<h4 class="title is-4">
  <a class="button is-danger" href="<%= new_user_registration_path %>">Sign Up</a>
     or
  <a class="button is-primary" href="<%= new_user_session_path %>">Sign In</a>
  to try
  <span style="color:royalblue">
    Projectify! A Project Management App
  </span>
  </br></h4>

<h4 class="subtitle">**Note: Still in development</h4>

<center>
  <%= image_tag("/images/web03team.png") %>
</center>

hello/app/views/hello/admin_panel.html.erb
<% if !user_signed_in? %>
  <%= render 'home' %>
  flash[:alert] = "If you are an Admin, Log In to see Admin Panel!"
<% else %>

    <div class="table-container">
  <table class="table">
      <thead>
      <tr>
        <th>Username</th>
        <th>Email</th>
        <th>Name</th>
        <th>Registration Date</th>
        <th>Status</th>
        <th>Action</th>
      </tr>
      </thead>
      <tbody>
      <% @users.all.each do |user| %>
        <tr>
          <td><%= h user.username %></td>
          <td><%= h user.email %></td>
          <td><%= h user.name %></td>
          <td><%= h user.created_at %></td>

          <% if user.is_active? %>
            <td style="color: green">Active User</td>
            <% else %>
            <td style="color: red">Banned User</td>
          <% end %>

          <% if user.is_active? %>
            <td>
                <b style="color: white">

                  <a id=user.id class="button is-danger" onclick="document.getElementById('id')"
                  <%= link_to "Ban", controller: :hello, :action => :admin_panel, :uid => user.id %>

                </b>
            </td>
          <% else %>
            <td>
                <b style="color: white">

                  <a id=user.id class="button is-success" onclick="document.getElementById('id')"
                  <%= link_to "Activate", controller: :hello, :action => :admin_panel, :uid => user.id %>

                </b>

            </td>
          <% end %>

      <% end %>

        </tr>
      </tbody>
    </table>
  </div>

  <h5><b>Number of New Users/Day</b></h5>
  <%= line_chart User.group_by_day(:created_at).count %>
  <h5><b>Number of Users/Team</b></h5>
  <%= pie_chart User.group(:team_id).count %>

  <b style="font-size: xx-large">
    <a href="https://mega.nz/file/90ljwaJS#bNB2OwR3VbiJA3kw6n8QSBzCMv_V57OQV9HKIokBfMk"><b>Database Dump</b></a>
  </b>
<% end %>

hello/app/views/hello/index.html.erb
<% if user_signed_in? %>
  <%= render 'dashboard' %>
<% else %>
  <%= render 'home' %>
<% end %>

hello/app/views/hello/ps1_scrape.html.erb
<h1>Scraping Fox News and CNN's Main Headlines and its Image</h1>
</br>

<p>Using Nokogiri, the HTML was parsed and using the full Xpath, the CSS selector element was identified to extract a particular attribute like text or img. The function was deployed in controller file and is rendered on this page.</p>

<b><h3>Fox News:</h3></b>
</br>

<b><%= @headline1 %></b>
<a href = <%= @headurl_1 %>>Link to Fox Article</a>
</br>
<img src= <%= @img_url1 %> style="width:650px;height:600px;"></img>

</br>
</br>

<h3>NDTV India News:</h3>
</br>

<b><%= @headline2 %></b>
<a href = <%= @headurl_2 %>>Link to NDTV Article</a>
</br>
<img src= <%= @img_url2 %> style="width:650px;height:600px;"></img>

hello/app/views/hello/ps1_zerodiv.html.erb
<h2>Zero Division Error Stack Trace</h2>

<%= 0/0 %>
<p>   
This Error stack was displayed by setting "config.consider_all_requests_local = true" in the "config/environments/production.rb" file.
</br>
</p>  

hello/app/views/hello/ps2_solutions.html.erb
<style>
pre { 
    white-space: pre-wrap; 
    word-break: break-word;
}

</style>

<a href="http://web3.cs.ait.ac.th/sql_files/ps2_ddl.txt"><b>SQL DDL (Text file transcript)</b></a>
</br>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Task</th>
      <th scope="col">Solution</th>
    </tr>
  </thead>
  <tbody>

    <tr>
      <th scope="row">1</th>
      <td><pre>Quotations</pre></td>
      <td><pre>Created a database and added a few quotes. 
By default, Active Record will use an integer column named id as the table's primary key (bigint for PostgreSQL and MySQL, integer for SQLite). When using Active Record Migrations to create your tables, this column will be automatically created.

References: <a href="https://edgeguides.rubyonrails.org/active_record_basics.html">Rails Active Record Basics</a>
</pre></td>
    </tr>

    <tr>
      <th scope="row">2</th>

      <td><pre>Select Box for existing categories and Text Filed for new categories</pre></td>
      
      <td><pre>The Rails ORM has a distinct function to select distinct categories which were used to retrieve for the Select Box.
If a new category is inputted in the text field, it is added to the database. Else, the category chosen in the Select Box is chosen.</pre> </td>
    </tr>

    <tr>
      <th scope="row">3</th>

      <td><pre>Search Box</pre></td>
      
      <td><pre>Search Box was created by using a form which submits the query term to a function "search". The search function has an SQL query that retrieves all data that contains the term in existing authors, quotes or categories.
</pre></td>
    </tr>


    <tr>
      <th scope="row">4</th>

      <td><pre>Kill / Delete</pre></td>
      
      <td><pre>A Kill switch was created for each quote which maps to the ID of the quote. When the "Delete" button is clicked, the ID of the quote deleted is stored in a cookie array. All the queries except those with IDs stored in the cookie are displayed. Personalization is restored even if the browser is restarted by using the cookie.permanent method.
</pre></td>
    </tr>


    <tr>
      <th scope="row">5</th>

      <td><pre>Exporting to XML/JSON format</pre></td>
      
      <td><pre>Using format method, both JSON and XML were rendered. For the XML to be hash resolved, JSON format was converted to XML.
</pre></td>
    </tr>


    <tr>
      <th scope="row">6</th>

      <td><pre>Importing the data</pre></td>
      
      <td><pre>A form to input the URL was provided and Nokogiri's css selector was used to grab the nodes that belong to the database.
</pre></td>
    </tr>


    <tr>
      <th scope="row">7</th>

      <td><pre>Loading data to database using text files</pre></td>
      
      <td><pre>$ cat mystocks.sql
create table my_stocks (
symbol varchar(20) not null,
n_shares integer not null,
date_acquired date not null
);

Input redirecting the file to psql DB

$ psql ps2 < mystocks.sql

Loading data into the table:

ps2=# copy my_stocks from '/home/deploy/hello/current/sql_files/data.txt' delimiter E',' NULL AS '\null';

ps2=# select * from my_stocks ;
 symbol | n_shares | date_acquired 
--------+----------+---------------
 GOGL   |     1234 | 2020-01-01
 NIFTY  |     2345 | 2020-05-04
 TSLA   |     3456 | 2019-12-09
 SPSX   |     4567 | 2020-08-01
 BLOR   |     5678 | 2019-12-01
 NASA   |     9876 | 2020-09-02
(6 rows)
</pre></td>
    </tr>


    <tr>
      <th scope="row">8</th>

      <td><pre>Copying data from one table to another</pre></td>
      
      <td><pre>ps2=# create table stock_prices as
ps2-# select symbol, current_date as quote_date ,30 as price
ps2-# from my_stocks;
SELECT 6


ps2=# select * from stock_prices;

 symbol | quote_date | price 
--------+------------+-------
 GOGL   | 2020-09-22 |    30
 NIFTY  | 2020-09-22 |    30
 TSLA   | 2020-09-22 |    30
 SPSX   | 2020-09-22 |    30
 BLOR   | 2020-09-22 |    30
 NASA   | 2020-09-22 |    30
(6 rows)


$ psql ps2 < newly_acquired.sql 
CREATE TABLE

ps2=# insert into newly_acquired_stocks (symbol, n_shares, date_acquired) select symbol, n_shares, date_acquired from my_stocks limit 3;
INSERT 0 3
ps2=# select * from newly_acquired_stocks;
 symbol | n_shares | date_acquired 
--------+----------+---------------
 GOGL   |     1234 | 2020-01-01
 NIFTY  |     2345 | 2020-05-04
 TSLA   |     3456 | 2019-12-09
(3 rows)
</pre></td>
    </tr>


    <tr>
      <th scope="row">9</th>

      <td><pre>JOIN</pre></td>
      
      <td><pre>ps2=# select my_stocks.symbol, my_stocks.n_shares, stock_prices.price, my_stocks.n_shares*stock_prices.price as value from my_stocks join stock_prices on stock_prices.symbol= my_stocks.symbol;

 symbol | n_shares | price | value  
--------+----------+-------+--------
 GOGL   |     1234 |    30 |  37020
 NIFTY  |     2345 |    30 |  70350
 TSLA   |     3456 |    30 | 103680
 SPSX   |     4567 |    30 | 137010
 BLOR   |     5678 |    30 | 170340
 NASA   |     9876 |    30 | 296280
(6 rows)

</pre></td>
    </tr>


    <tr>
      <th scope="row">10</th>

      <td><pre>OUTER JOIN</pre></td>
      
      <td><pre>Inserting a new record into my_stocks table using INSERT:

ps2=# insert into my_stocks (symbol, n_shares, date_acquired)
ps2-# values('BTC', 1000, '03/05/2020');
INSERT 0 1


Joining the stock_prices and my_stocks table using symbol column

ps2=# select my_stocks.symbol, my_stocks.n_shares, stock_prices.price, my_stocks.n_shares*stock_prices.price as value from my_stocks join stock_prices on stock_prices.symbol= my_stocks.symbol;
 symbol | n_shares | price | value  
--------+----------+-------+--------
 GOGL   |     1234 |    30 |  37020
 NIFTY  |     2345 |    30 |  70350
 TSLA   |     3456 |    30 | 103680
 SPSX   |     4567 |    30 | 137010
 BLOR   |     5678 |    30 | 170340
 NASA   |     9876 |    30 | 296280
(6 rows)

The new record "BTC" inserted is not shown.

Using the FULL JOIN to show all the stocks

ps2=# select my_stocks.symbol, my_stocks.n_shares, stock_prices.price, my_stocks.n_shares*stock_prices.price as value
ps2-# from my_stocks
ps2-# full join stock_prices on stock_prices.symbol= my_stocks.symbol;
 symbol | n_shares | price | value  
--------+----------+-------+--------
 GOGL   |     1234 |    30 |  37020
 NIFTY  |     2345 |    30 |  70350
 TSLA   |     3456 |    30 | 103680
 SPSX   |     4567 |    30 | 137010
 BLOR   |     5678 |    30 | 170340
 NASA   |     9876 |    30 | 296280
 BTC    |     1000 |       |       
(7 rows)
</pre></td>
    </tr>


    <tr>
      <th scope="row">11</th>

      <td><pre>PL/SQL:</pre></td>
      
      <td><pre>/* ascii_sum function */

CREATE OR REPLACE FUNCTION ascii_sum (sym TEXT)
RETURNS integer AS $sum$
declare
sum integer;
BEGIN
  select sum(ascii(regexp_split_to_table)) from regexp_split_to_table(sym, '') into sum;
  RETURN sum;
END;
$sum$ LANGUAGE plpgsql;

Updating all stock prices using ascii_sum function. (Adding ascii value of characters in Symbol)

ps2=# UPDATE stock_prices
SET price = ascii_sum (symbol);
UPDATE 6

ps2=# select * from stock_prices ;
 symbol | quote_date | price 
--------+------------+-------
 GOGL   | 2020-09-22 |   297
 NIFTY  | 2020-09-22 |   394
 TSLA   | 2020-09-22 |   308
 SPSX   | 2020-09-22 |   334
 BLOR   | 2020-09-22 |   303
 NASA   | 2020-09-22 |   291
(6 rows)
</pre></td>
    </tr>


    <tr>
      <th scope="row">12</th>

      <td><pre>Buy More of Winners</pre></td>
      
      <td><pre>Average price of holdings:

ps2=# select avg(price) from stock_prices;
         avg          
----------------------
 321.1666666666666667
 
Doubling holdings greater than average price

ps2=# insert into my_stocks (symbol, n_shares, date_acquired)
select m.symbol, m.n_shares, current_date from my_stocks as m
where m.symbol in (select s.symbol from stock_prices as s where s.price > 321.16);
INSERT 0 2


ps2=# select * from my_stocks;
 symbol | n_shares | date_acquired 
--------+----------+---------------
 GOGL   |     1234 | 2020-01-01
 NIFTY  |     2345 | 2020-05-04
 TSLA   |     3456 | 2019-12-09
 SPSX   |     4567 | 2020-08-01
 BLOR   |     5678 | 2019-12-01
 NASA   |     9876 | 2020-09-02
 BTC    |     1000 | 2020-05-03
 NIFTY  |     2345 | 2020-09-22
 SPSX   |     4567 | 2020-09-22
(9 rows)


Outer join: 

ps2=# select m.symbol, m.n_shares, price from my_stocks m FULL JOIN stock_prices s on m.symbol = s.symbol;
 symbol | n_shares | price 
--------+----------+-------
 GOGL   |     1234 |   297
 NIFTY  |     2345 |   394
 TSLA   |     3456 |   308
 SPSX   |     4567 |   334
 BLOR   |     5678 |   303
 NASA   |     9876 |   291
 BTC    |     1000 |      
 NIFTY  |     2345 |   394
 SPSX   |     4567 |   334
(9 rows)

Total Share Holding:

ps2=# select symbol, sum(n_shares) as total_no_shares from my_stocks group by symbol;
 symbol | total_no_shares 
--------+-----------------
 NASA   |            9876
 SPSX   |            9134
 BTC    |            1000
 NIFTY  |            4690
 GOGL   |            1234
 BLOR   |            5678
 TSLA   |            3456
(7 rows)

Total value of holdings:

ps2=# select m.symbol, sum(m.n_shares*s.price) as value from my_stocks m
ps2-# inner join stock_prices s on m.symbol = s.symbol group by m.symbol;
 symbol |  value  
--------+---------
 BLOR   | 1720434
 GOGL   |  366498
 NASA   | 2873916
 NIFTY  | 1847860
 SPSX   | 3050756
 TSLA   | 1064448
(6 rows)

Total Shares of Winners and their value:

ps2=# select m.symbol, sum(m.n_shares) as total_shares, sum(m.n_shares * s.price) as value from my_stocks m
ps2-# inner join stock_prices s on m.symbol = s.symbol group by m.symbol having count(*) >=2
ps2-# ;
 symbol | total_shares |  value  
--------+--------------+---------
 NIFTY  |         4690 | 1847860
 SPSX   |         9134 | 3050756
(2 rows)</pre></td>
    </tr>


    <tr>
      <th scope="row">13</th>

      <td><pre>Encapsulating queries with a view:</pre></td>
      
      <td>
        <pre>ps2=# create view stocks_i_like as select m.symbol, sum(m.n_shares) as
ps2-# total_shares, sum(n_shares*s.price) as total_value from my_stocks m
ps2-# inner join stock_prices s on m.symbol = s.symbol group by m.symbol having count(*) >=2;
CREATE VIEW
        </pre>
      </td>
    </tr>


    





    
  </tbody>
</table>

hello/app/views/hello/quotations.html.erb
<h3>Quotations</h3>


<%= form_tag quotations_search_path, :method => "get" do %>
	<%= label_tag(:search, "Search Quote") %>
	<%= text_field_tag :search, params[:search] %>
	<%= submit_tag("Search", name: nil) %>
<% end %>

</br>

<% if cookies[:qno] != "" or cookies[:qno] != nil %>
     <td><%= link_to "Erase My Personalization", :action => :quotations, :erase => 1 %></td>
<% end %>


</br>
<td><%= link_to "Export to XML", quotations_path+".xml" %></td>
</br>
<td><%= link_to "Export to JSON", quotations_path+".json" %></td>
</br>


<%= form_tag quotations_path, :method => "get" do %>
	<%= text_field_tag :xml_url %>
	<%= submit_tag("Import XML", name: nil) %>
<% end %>


</br>
</br>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Author</th>
      <th scope="col">Quote</th>
      <th scope="col">Category</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>

  	<% for quotation in @quotations %>
		
	    <tr>
	      <td><%= h quotation.author_name %></td>
	      <td><%= h quotation.quote %></td>
	      <td><%= h quotation.category %></td>
	      <td><%= link_to "Delete", :action => :quotations, :qno => quotation.id %></td>
	    </tr>

    <% end %>

  </tbody>
</table>


<br/>

<%= cookies[:qno] %>

<% if params[:sort_by] == "date" %>
	<%= link_to "Sort by category", :action => :quotations, :sort_by => :category %>
<% else %>
	<%= link_to "Sort by date", :action => :quotations, :sort_by => :date %>
<% end %>

<hr/>






<h3>New quotation</h3>

<%= form_for @quotation, :url => { :action => :quotations } do |form| %>
	<% @quotation.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>

<fieldset>
	<legend>Enter details</legend>
	
	<div class="form_row">
		<%= form.label :author_name %>
		<%= form.text_field :author_name, :size => 20, :maxlength => 40 %>
	</div>
	
		<div class ="form_row">
			<%= form.label :category %>
			<%= form.select :category, Quotation.all.collect {|q| q.category }.uniq %>
		</div>


	<div class="form_row">
		<%= form.label :newcategory %>
		<%= text_field :newcategory, :id %>
	</div>


	<div class="form_row">
		<%= form.label :quote %>
		<%= form.text_area :quote, :rows => 2, :cols => 40, :maxlength => 500 %>
	</div>

</fieldset>

<p>
<div class="form_row">
	<%= form.submit 'Create' %>
</div>
</p>

<% end %>

hello/app/views/hello/searchpage.html.erb
</br>
<h2>Search Results:</h2>
</br>
<%= form_tag quotations_search_path, :method => "get" do %>
	<%= label_tag(:search, "Search Quote") %>
	<%= text_field_tag :search, params[:search] %>
	<%= submit_tag("Search", name: nil) %>
<% end %>
</br>
<h3>Quotations</h3>
<ul>
	<% for quotation in @quotations %>
		<li><%= h quotation.author_name %>: <%= h quotation.quote %></li>
	<% end %>
</ul>

<a href="/quotations" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Go Back to Quotations Page</a>

</br>