hello/config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :projects

  devise_for :users


  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :projects
  resources :teams
  resources :users

  root 'hello#index'

  get 'ps1_zerodiv', to: 'hello#zerodiv', as: 'zerodiv'

  get 'ps1_scrape', to: 'hello#scrape', as: 'scrape'

  get 'quotations', to: 'hello#quotations', as: 'quotations'

  post 'quotations', to: 'hello#quotations', as: 'quotations_post'

  get 'searchpage', to: 'hello#searchpage', as: 'quotations_search'

  get 'ps2_solutions', to: 'hello#ps2_solutions', as: 'ps2_sol'

  get 'ps3', to: 'hello#ps3', as: 'ps3'

  get 'ps4', to: 'hello#ps4', as: 'ps4'

  get 'ps5', to: 'hello#ps5', as: 'ps5'

  get 'ps6', to: 'hello#ps6', as: 'ps6'


  get 'admin_panel', to: 'hello#admin_panel', as: 'admin_panel'
  post 'admin_panel', to: 'hello#admin_panel', as: 'admin_panel_post'


end

hello/app/views/layouts/_flash.html.erb
<% if notice || alert %>
  <script>
      window.onload = function(){
          var hideMe = document.getElementById('hideMe');
          document.onclick = function(e){
              if(e.target.id !== 'hideMe'){
                  hideMe.style.display = 'none';
              }
          };
      };
  </script>
  <div id="hideMe" class="flash-message
  <%= notice ? "notice" : ""%>
  <%= alert ? "error" : ""%>">
    <div class="container container_12 clearfix">
      <div class="grid_12">
        <% if notice %> <p><%= notice %></p>
        <% elsif alert %> <p><%= alert %></p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

hello/app/views/layouts/_navbar.html.erb
<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">

    <a class="navbar-item" href="/">
      Web 3
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">

    <div class="navbar-start">
      <a class="navbar-item" href="/">
        <span class="icon">
          <i class="fas fa-home"></i>
        </span>
        Home
      </a>


      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          PS 1
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item" href="/ps1_zerodiv">
            Zero Division
          </a>
          <a class="navbar-item" href="/ps1_scrape">
            Scraping
          </a>
        </div>
      </div>


      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          PS 2
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item" href="/quotations">
            Quotations
          </a>
          <a class="navbar-item" href="/ps2_solutions">
          Solutions
          </a>
          <a class="navbar-item" href="/ps2_ddl.txt">
            SQL Resource
          </a>
        </div>
      </div>


      <a class="navbar-item" href="/ps3">
        PS 3
      </a>

      <a class="navbar-item" href="/ps4">
        PS 4
      </a>

      <a class="navbar-item" href="/ps5">
        PS 5
      </a>

      <a class="navbar-item" href="/ps6">
        PS 6
      </a>





    </div>

    <div id="navbar" class="navbar-menu">
      <div class="navbar-end">
        <% if user_signed_in? %>

          <% if current_user.is_admin? %>
            <div class="navbar-item">
              <div class="buttons">
                <a class="button is-warning" href="<%= admin_panel_path %>"><strong>Admin Panel</strong></a>
              </div>
            </div>
          <% end %>


          <div class="navbar-item has-dropdown is-hoverable">
            <div class="buttons">
              <a class="button is-info" href="#"><strong>New</strong></a>
              <div class="navbar-dropdown">
                <div class="buttons">
                  <a class="button is-info is-light" href="<%= new_project_path %>"><strong>Project</strong></a>
                  <a class="button is-info is-light" href="<%= new_team_path %>"><strong>Team</strong></a>
                </div>
              </div>
            </div>
          </div>
          <div class="navbar-item has-dropdown is-hoverable">
            <div class="buttons">
              <a class="button is-primary" href="#"><strong>Account</strong></a>
              <div class="navbar-dropdown">
                <div class="buttons">
                  <a class="button is-primary is-light" href="<%= edit_user_registration_path %>">
                    <strong>Edit Account</strong>
                  </a>
                  <a class="button is-danger is-light" formmethod="delete" onclick="location.href='<%= destroy_user_session_path %>'">
                    <strong>Log Out</strong>
                  </a>
                  <%#= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                </div>
              </div>
            </div>
          </div>
          <% else %>
            <div class="navbar-item">
              <div class="buttons">
                <a class="button is-danger" href="<%= new_user_registration_path %>"><strong>Sign Up</strong></a>
                <a class="button is-primary" href="<%= new_user_session_path %>"><strong>Sign In</strong></a>
              </div>
            </div>

            </div>
          <% end %>

      </div>
    </div>


  </div>


</nav>

hello/app/views/layouts/_xhtml_validator.html.erb
   <p>
      <a href="https://validator.w3.org/check?uri=referer"><img
          src="http://www.w3.org/Icons/valid-xhtml10"
          alt="Valid XHTML 1.0!" height="31" width="88" /></a>
    </p>

hello/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Sidapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'projectify' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash' %>
  </br>

  <div class="content-wrap">
    <%= yield %>
  </div>

  <footer class="navbar fixed-bottom navbar-dark bg-dark">
    <div class="column is-half has-text-light">
      Developed by <b>Thoviti Siddharth</b> - st121362
    </div>
    <div class="column is-half has-text-right">
      <%= render 'layouts/xhtml_validator' %>
    </div>
  </footer>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>